### ISSUE TITLE
What is the starting height of the Stxmap index?

### ISSUE THREAD

**Issue by kimberlyedwards1014459** [fess-v/stx20-standard#2]
I developed an indexer but I don't know from which height I should start indexing

**Comment by fess-v** [comment]
132354 block, https://github.com/fess-v/stx20-standard/blob/main/stxsip-proposals/stxsip-001_stxmap.md explanation is there @kimberlyedwards1014459

**Comment by kimberlyedwards1014459** [comment]
thanks
