### ISSUE TITLE
`Ticker does not exist` even though it shows up on satscreener.com

### ISSUE THREAD

**Issue by matronator** [fess-v/stx20-standard#5]
I inscribed some tokens, the transaction went through and got confirmed on the network. It even shows up on satscreener.com. However when I go to the Mint tab to mint it, it says that `Ticker does not exist`.

How? Why?

**Comment by fess-v** [comment]
what ticker? so we can take a look @matronator 
You can create a ticket in our discord or write me there if you want

**Comment by matronator** [comment]
It's there, it looks like it was just a bit delayed. Thanks!
